/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) Mark Johnston <markj@FreeBSD.org>
 */

#include <errno.h>

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

int	luaopen_errno(lua_State *L);

int
luaopen_errno(lua_State *L)
{
	lua_newtable(L);

#define	ADDERRNO(name) 			\
	lua_pushinteger(L, name);	\
	lua_setfield(L, -2, #name)
	ADDERRNO(EPERM);
	ADDERRNO(ENOENT);
	ADDERRNO(ESRCH);
	ADDERRNO(EINTR);
	ADDERRNO(EIO);
	ADDERRNO(ENXIO);
	ADDERRNO(E2BIG);
	ADDERRNO(ENOEXEC);
	ADDERRNO(EBADF);
	ADDERRNO(ECHILD);
	ADDERRNO(EDEADLK);
	ADDERRNO(ENOMEM);
	ADDERRNO(EACCES);
	ADDERRNO(EFAULT);
	ADDERRNO(ENOTBLK);
	ADDERRNO(EBUSY);
	ADDERRNO(EEXIST);
	ADDERRNO(EXDEV);
	ADDERRNO(ENODEV);
	ADDERRNO(ENOTDIR);
	ADDERRNO(EISDIR);
	ADDERRNO(EINVAL);
	ADDERRNO(ENFILE);
	ADDERRNO(EMFILE);
	ADDERRNO(ENOTTY);
	ADDERRNO(ETXTBSY);
	ADDERRNO(EFBIG);
	ADDERRNO(ENOSPC);
	ADDERRNO(ESPIPE);
	ADDERRNO(EROFS);
	ADDERRNO(EMLINK);
	ADDERRNO(EPIPE);
	ADDERRNO(EDOM);
	ADDERRNO(ERANGE);
	ADDERRNO(EAGAIN);
	ADDERRNO(EWOULDBLOCK);
	ADDERRNO(EINPROGRESS);
	ADDERRNO(EALREADY);
	ADDERRNO(ENOTSOCK);
	ADDERRNO(EDESTADDRREQ);
	ADDERRNO(EMSGSIZE);
	ADDERRNO(EPROTOTYPE);
	ADDERRNO(ENOPROTOOPT);
	ADDERRNO(EPROTONOSUPPORT);
	ADDERRNO(ESOCKTNOSUPPORT);
	ADDERRNO(EOPNOTSUPP);
	ADDERRNO(ENOTSUP);
	ADDERRNO(EPFNOSUPPORT);
	ADDERRNO(EAFNOSUPPORT);
	ADDERRNO(EADDRINUSE);
	ADDERRNO(EADDRNOTAVAIL);
	ADDERRNO(ENETDOWN);
	ADDERRNO(ENETUNREACH);
	ADDERRNO(ENETRESET);
	ADDERRNO(ECONNABORTED);
	ADDERRNO(ECONNRESET);
	ADDERRNO(ENOBUFS);
	ADDERRNO(EISCONN);
	ADDERRNO(ENOTCONN);
	ADDERRNO(ESHUTDOWN);
	ADDERRNO(ETOOMANYREFS);
	ADDERRNO(ETIMEDOUT);
	ADDERRNO(ECONNREFUSED);
	ADDERRNO(ELOOP);
	ADDERRNO(ENAMETOOLONG);
	ADDERRNO(EHOSTDOWN);
	ADDERRNO(EHOSTUNREACH);
	ADDERRNO(ENOTEMPTY);
	ADDERRNO(EPROCLIM);
	ADDERRNO(EUSERS);
	ADDERRNO(EDQUOT);
	ADDERRNO(ESTALE);
	ADDERRNO(EREMOTE);
	ADDERRNO(EBADRPC);
	ADDERRNO(ERPCMISMATCH);
	ADDERRNO(EPROGUNAVAIL);
	ADDERRNO(EPROGMISMATCH);
	ADDERRNO(EPROCUNAVAIL);
	ADDERRNO(ENOLCK);
	ADDERRNO(ENOSYS);
	ADDERRNO(EFTYPE);
	ADDERRNO(EAUTH);
	ADDERRNO(ENEEDAUTH);
	ADDERRNO(EIDRM);
	ADDERRNO(ENOMSG);
	ADDERRNO(EOVERFLOW);
	ADDERRNO(ECANCELED);
	ADDERRNO(EILSEQ);
	ADDERRNO(ENOATTR);
	ADDERRNO(EDOOFUS);
	ADDERRNO(EBADMSG);
	ADDERRNO(EMULTIHOP);
	ADDERRNO(ENOLINK);
	ADDERRNO(EPROTO);
	ADDERRNO(ENOTCAPABLE);
	ADDERRNO(ECAPMODE);
	ADDERRNO(ENOTRECOVERABLE);
	ADDERRNO(EOWNERDEAD);
	ADDERRNO(EINTEGRITY);
	ADDERRNO(ELAST);
#undef ADDERRNO

	return (1);
}
